# Generated by Django 5.1.10 on 2025-08-30 15:48

from django.db import migrations, models


def assign_default_roles(apps, schema_editor):
    OrganizationMember = apps.get_model("organizations", "OrganizationMember")
    for member in OrganizationMember.objects.select_related("organization"):
        role = "admin" if member.user_id == member.organization.created_by_id else "member"
        OrganizationMember.objects.filter(pk=member.pk).update(role=role)


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0006_alter_organizationmember_deleted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationmember",
            name="role",
            field=models.CharField(
                choices=[("member", "Member"), ("admin", "Admin")],
                default="member",
                max_length=16,
            ),
        ),
        migrations.RunPython(assign_default_roles, migrations.RunPython.noop),
    ]
